source "https://rubygems.org"

gem "rails", "~> 8.1.3"
gem "puma", ">= 5.0"

gem "igniter-contracts", path: "../../packages/igniter-contracts"
gem "igniter-embed", path: "../../packages/igniter-embed"
gem "igniter-extensions", path: "../../packages/igniter-extensions"
gem "igniter-ledger", path: "../../packages/igniter-ledger"
gem "igniter-ledger-client", path: "../../packages/igniter-ledger-client"

gem "tzinfo-data", platforms: %i[windows jruby]

group :development, :test do
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
end

group :development do
  gem "web-console"
end
