# frozen_string_literal: true

source "https://rubygems.org"

gem "igniter", path: "../.."

group :development, :test do
  gem "rspec"
end

# Optional:
# gem "puma"   # production HTTP server  →  bundle exec puma config.ru
