services:
  main:
    build:
      context: ../../../../
      dockerfile: examples/companion/config/deploy/Dockerfile
    command: bundle exec ruby workspace.rb main
    working_dir: /app/examples/companion
    environment:
      COMPANION_DATA_ADAPTER: sqlite
      COMPANION_DATA_DB: var/companion_data.sqlite3
      COMPANION_EXECUTION_ADAPTER: sqlite
      COMPANION_EXECUTION_DB: var/main_executions.sqlite3
      PORT: 4567
    ports:
      - "4567:4567"
    volumes:
      - companion_var:/app/examples/companion/var
    depends_on:
      - inference

  inference:
    build:
      context: ../../../../
      dockerfile: examples/companion/config/deploy/Dockerfile
    command: bundle exec ruby workspace.rb inference
    working_dir: /app/examples/companion
    environment:
      COMPANION_DATA_ADAPTER: sqlite
      COMPANION_DATA_DB: var/companion_data.sqlite3
      COMPANION_EXECUTION_ADAPTER: sqlite
      COMPANION_EXECUTION_DB: var/inference_executions.sqlite3
      PORT: 4568
    ports:
      - "4568:4568"
    volumes:
      - companion_var:/app/examples/companion/var

  dashboard:
    build:
      context: ../../../../
      dockerfile: examples/companion/config/deploy/Dockerfile
    command: bundle exec ruby workspace.rb dashboard
    working_dir: /app/examples/companion
    environment:
      COMPANION_DATA_ADAPTER: sqlite
      COMPANION_DATA_DB: var/companion_data.sqlite3
      COMPANION_EXECUTION_ADAPTER: sqlite
      COMPANION_EXECUTION_DB: var/dashboard_executions.sqlite3
      PORT: 4569
    ports:
      - "4569:4569"
    volumes:
      - companion_var:/app/examples/companion/var
    depends_on:
      - main

volumes:
  companion_var:
