---
services:
  main:
    build:
      context: "../../../../"
      dockerfile: examples/companion/config/deploy/Dockerfile
    command: bundle exec ruby stack.rb --service main
    working_dir: "/app/examples/companion"
    environment:
      COMPANION_DATA_ADAPTER: sqlite
      COMPANION_DATA_DB: var/companion_data.sqlite3
      COMPANION_EXECUTION_ADAPTER: sqlite
      COMPANION_EXECUTION_DB: var/main_executions.sqlite3
      IGNITER_APP: main
      IGNITER_SERVICE: main
      PORT: '4567'
      IGNITER_TOPOLOGY_PROFILE: local-compose
    ports:
    - 4567:4567
    depends_on:
    - inference
    volumes:
    - companion_var:/app/examples/companion/var
  inference:
    build:
      context: "../../../../"
      dockerfile: examples/companion/config/deploy/Dockerfile
    command: bundle exec ruby stack.rb --service inference
    working_dir: "/app/examples/companion"
    environment:
      COMPANION_DATA_ADAPTER: sqlite
      COMPANION_DATA_DB: var/companion_data.sqlite3
      COMPANION_EXECUTION_ADAPTER: sqlite
      COMPANION_EXECUTION_DB: var/inference_executions.sqlite3
      IGNITER_APP: inference
      IGNITER_SERVICE: inference
      PORT: '4568'
      IGNITER_TOPOLOGY_PROFILE: local-compose
    volumes:
    - companion_var:/app/examples/companion/var
  dashboard:
    build:
      context: "../../../../"
      dockerfile: examples/companion/config/deploy/Dockerfile
    command: bundle exec ruby stack.rb --service dashboard
    working_dir: "/app/examples/companion"
    environment:
      COMPANION_DATA_ADAPTER: sqlite
      COMPANION_DATA_DB: var/companion_data.sqlite3
      COMPANION_EXECUTION_ADAPTER: sqlite
      COMPANION_EXECUTION_DB: var/dashboard_executions.sqlite3
      IGNITER_APP: dashboard
      IGNITER_SERVICE: dashboard
      PORT: '4569'
      IGNITER_TOPOLOGY_PROFILE: local-compose
    ports:
    - 4569:4569
    depends_on:
    - main
    volumes:
    - companion_var:/app/examples/companion/var
volumes:
  companion_var: {}
